ARCHS = arm64 arm64e
TARGET = iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = NSNotifExampleSwift

APPLICATION_NAME = NSNotifExampleSwift

NSNotifExampleSwift_FILES = Core/AppDelegate.swift Controllers/FirstVC.swift Controllers/SecondVC.swift Controllers/TabBarVC.swift Extensions/Extensions.swift
NSNotifExampleSwift_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
