ARCHS = arm64 arm64e
TARGET = iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = WeatherMVVM

APPLICATION_NAME = WeatherMVVM

WeatherMVVM_FILES = Core/WeatherMVVM.swift Models/WeatherModel.swift ViewModels/WeatherViewModel.swift Views/ContentView.swift

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
