ARCHS = arm64 arm64e
TARGET = iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = Aurora

APPLICATION_NAME = Aurora

Aurora_FILES = Core/Aurora.swift CustomModifiers/CustomModifiers.swift Views/ContentView.swift Views/VaultView.swift

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
