ARCHS = arm64 arm64e
TARGET = iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = Aurora

APPLICATION_NAME = Aurora

Aurora_FILES = Core/AppDelegate.swift Controllers/AuroraRootVC.swift Controllers/AuroraVC.swift Controllers/SettingsVC.swift Managers/ColorManager.swift
Aurora_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
