ARCHS = arm64 arm64e
TARGET = iphone:clang:latest:latest
INSTALL_TARGET_PROCESSES = NSNotifExample

APPLICATION_NAME = NSNotifExample

NSNotifExample_FILES = Core/AppDelegate.swift Controllers/FirstVC.swift Controllers/SecondVC.swift Controllers/TabBarVC.swift Extensions/Extensions.swift
NSNotifExample_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
