TARGET = iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = Cathal

APPLICATION_NAME = Cathal

Cathal_FILES = ContentView.swift CathalApp.swift ProgressView.swift

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
